"""rev

Revision ID: c9df39dd17fa
Revises: b9afc90a6067
Create Date: 2025-05-29 13:08:03.924564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9df39dd17fa'
down_revision = 'b9afc90a6067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
