"""r

Revision ID: 72616e67c473
Revises: a4e2fd0e997b
Create Date: 2025-05-29 12:50:29.540923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72616e67c473'
down_revision = 'a4e2fd0e997b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
