"""create tubes_user table

Revision ID: 7908d69aed4b
Revises: 
Create Date: 2025-05-27 20:56:57.000907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7908d69aed4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_index('my_index', 'models', ['name'], unique=True, mysql_length=255)
    op.create_table('tubes_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.Text(), nullable=False),
    sa.Column('nama', sa.Text(), nullable=False),
    sa.Column('jurusan', sa.Text(), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tubes_user')),
    sa.UniqueConstraint('nim', name=op.f('uq_tubes_user_nim'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tubes_user')
    op.drop_index('my_index', table_name='models', mysql_length=255)
    op.drop_table('models')
    # ### end Alembic commands ###
