"""create mahasiswa table

Revision ID: 64827c4332e5
Revises: 46121ae194ab
Create Date: 2025-05-29 13:19:46.403565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64827c4332e5'
down_revision = '46121ae194ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
