"""create tables

Revision ID: 6777b359d0b3
Revises: 87e73fa18956
Create Date: 2025-05-28 00:58:54.483683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6777b359d0b3'
down_revision = '87e73fa18956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acara',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gambar_file', sa.String(), nullable=True),
    sa.Column('judul', sa.String(), nullable=True),
    sa.Column('konten', sa.Text(), nullable=True),
    sa.Column('tanggal_acara', sa.Date(), nullable=True),
    sa.Column('jenis_acara', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acara'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acara')
    # ### end Alembic commands ###
