"""rev

Revision ID: 46121ae194ab
Revises: c9df39dd17fa
Create Date: 2025-05-29 13:13:55.695017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46121ae194ab'
down_revision = 'c9df39dd17fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
