"""rev

Revision ID: b9afc90a6067
Revises: dc50e9a84e3a
Create Date: 2025-05-29 13:05:20.625781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9afc90a6067'
down_revision = 'dc50e9a84e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
