"""create tubes_user table

Revision ID: f0e862cc2acd
Revises: 7908d69aed4b
Create Date: 2025-05-27 21:22:52.657708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e862cc2acd'
down_revision = '7908d69aed4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
