"""add email and password to tubes_user

Revision ID: 8645a14cd27c
Revises: 54a764c2edaf
Create Date: 2025-05-27 21:53:02.417148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8645a14cd27c'
down_revision = '54a764c2edaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tubes_user', sa.Column('password', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tubes_user', 'password')
    # ### end Alembic commands ###
