"""create tubes_user table

Revision ID: 54a764c2edaf
Revises: f0e862cc2acd
Create Date: 2025-05-27 21:36:52.496015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a764c2edaf'
down_revision = 'f0e862cc2acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tubes_user', sa.Column('email', sa.Text(), nullable=True))
    op.create_unique_constraint(op.f('uq_tubes_user_email'), 'tubes_user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_tubes_user_email'), 'tubes_user', type_='unique')
    op.drop_column('tubes_user', 'email')
    # ### end Alembic commands ###
