"""add pict

Revision ID: 9c55a07e226a
Revises: 868268febf57
Create Date: 2025-05-28 01:28:04.097591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c55a07e226a'
down_revision = '868268febf57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
