"""r

Revision ID: a4e2fd0e997b
Revises: 9c55a07e226a
Create Date: 2025-05-28 13:49:41.252546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e2fd0e997b'
down_revision = '9c55a07e226a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
