"""nah

Revision ID: ede2b29fbb59
Revises: 64827c4332e5
Create Date: 2025-05-29 13:22:54.082617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede2b29fbb59'
down_revision = '64827c4332e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
