"""create tables

Revision ID: 868268febf57
Revises: 6777b359d0b3
Create Date: 2025-05-28 00:59:42.199391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868268febf57'
down_revision = '6777b359d0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
