"""nah

Revision ID: 039284fbdd06
Revises: 757944ec86ac
Create Date: 2025-05-29 13:40:54.989972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039284fbdd06'
down_revision = '757944ec86ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
