"""init

Revision ID: 2cd2bcea3418
Revises: 039284fbdd06
Create Date: 2025-05-29 13:48:59.432308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd2bcea3418'
down_revision = '039284fbdd06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
