"""rev

Revision ID: dc50e9a84e3a
Revises: 72616e67c473
Create Date: 2025-05-29 12:54:07.255983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc50e9a84e3a'
down_revision = '72616e67c473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
