"""init

Revision ID: 978c031000cb
Revises: 2cd2bcea3418
Create Date: 2025-05-29 13:51:29.686335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978c031000cb'
down_revision = '2cd2bcea3418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
